[project]
name = "cocreate"
version = "0.1.0"
description = "cocreate using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=0.140.0,<1.0.0",
    "langfuse>=3.2.1",
    "openinference-instrumentation-crewai>=0.1.11",
    "openinference-instrumentation-litellm>=0.1.24",
]

[project.scripts]
cocreate = "cocreate.main:run"
run_crew = "cocreate.main:run"
train = "cocreate.main:train"
replay = "cocreate.main:replay"
test = "cocreate.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
